# Generated by Django 5.2 on 2025-05-04 23:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=3)),
                ('cca3', models.CharField(max_length=3)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('area', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('flag_png', models.URLField(blank=True, max_length=500, null=True)),
                ('flag_svg', models.URLField(blank=True, max_length=500, null=True)),
                ('borders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None)),
                ('languages', models.JSONField()),
                ('currencies', models.JSONField()),
                ('maps_google', models.URLField(blank=True, null=True)),
                ('maps_osm', models.URLField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('tlds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
            ],
        ),
    ]
